### PR TITLE
Add la palma & outreach information 

### PR DESCRIPTION
**Pull request by Carter90**

### CODE REVIEW

**Comment by johncarl81** [comment]
Curious where you found that La Palma image @Carter90

**Comment by johncarl81** [comment]
For these subsections, I was thinking that they would have at least a synopsis on the home page with links to the subpages [here](https://github.com/BCLab-UNM/volcan_website/blob/master/index.html#L161).  WDYT @Carter90 ?

**Comment by Carter90** [comment]
> Curious where you found that La Palma image @Carter90
Well @johncarl81, 
From @gmfricke "Please add a la palma volcano image to the image playlist. "
"Probably not the best photo we have but it’s not bad"
https://unm-volcan.slack.com/archives/C03GT4SUD7T/p1653149580100519

**Comment by johncarl81** [comment]
Cool, ok, just double checking that it was from our media - I didn't recognize it immediately.

**Comment by Carter90** [comment]
> For these subsections, I was thinking that they would have at least a synopsis on the home page with links to the subpages [here](https://github.com/BCLab-UNM/volcan_website/blob/master/index.html#L161). WDYT @Carter90 ?

Sure I'll need blurbs to put there

**Comment by johncarl81** [comment]
@gmfricke, would you provide some text?

**Comment by johncarl81** [comment]
Oh, and @gmfricke may have some images for the outreach event (just came across the email request from matthew):

> Melanie asked for an outreach “tab” on the VolCAN website. I will send you some pics from the outreach event at Bandelier to put on it when you are ready. NSF is excited about things like that.

**Comment by Carter90** [comment]
> Oh, and @gmfricke may have some images for the outreach event (just came across the email request from matthew):
> 
> > Melanie asked for an outreach “tab” on the VolCAN website. I will send you some pics from the outreach event at Bandelier to put on it when you are ready. NSF is excited about things like that.

Right Matthew posted a bunch but I asked him to pick which ones due to privacy concerns.

**Comment by Carter90** [comment]
## TODO 
- [x] Fold all pages into home except personnel
- [x] Add image from Bandelier
- [x] Add myself to personnel
- [x] La Palma section text blerb
- [ ] Update/Add Images (That first image remove?)

@johncarl81 & @gmfricke am I missing anything?

**Comment by Carter90** [comment]
@gmfricke @johncarl81 Anything else?

**Review by johncarl81 — APPROVED** [review]

**Pull request merged**
